Use Debian kernel and u-boot for Raspberry Pi 2 - Create /boot/firmware partition as vfat - Use ext2 for /boot - Use u-boot-rpi and armmp kernel - Use flash-kernel to copy kernel to /boot

diff --git a/freedommaker/freedombox-customize b/freedommaker/freedombox-customize
--- a/freedommaker/freedombox-customize
+++ b/freedommaker/freedombox-customize
@@ -97,6 +97,12 @@ unmount_file_systems() {
     umount "$rootdir/dev" || true
     umount "$rootdir/proc" || true
     umount "$rootdir/sys" || true
+
+    case "$MACHINE" in
+	raspberry2)
+	    umount "$rootdir/boot/firmware" || true
+	    ;;
+    esac
 }
 
 # Set to true/false to control if eatmydata is used during build
@@ -104,6 +110,33 @@ use_eatmydata=true
 
 rootdir="$1"
 image="$(cd "$(dirname "$2")"; pwd)/$(basename "$2")"
+
+# Create vfat /boot/firmware partition for devices that need it.
+case "$MACHINE" in
+    raspberry2)
+	umount "$rootdir/boot"
+	umount "$rootdir"
+	kpartx -dvs "$image"
+
+	parted -s "$image" mkpart primary 0% 128MiB
+
+	# Reorder partitions by start offset
+	sfdisk --reorder "$image"
+
+	device=/dev/mapper/$(kpartx -avs "$image" \
+				    | awk '/^add map / {print $3; exit}')
+	mkfs -t vfat "$device"
+
+	mount -t btrfs "${device%?}3" "$rootdir"
+	mount -t ext2 "${device%?}2" "$rootdir"/boot
+	mkdir "$rootdir/boot/firmware"
+	mount -t vfat "$device" "$rootdir/boot/firmware"
+
+	fs_uuid=$(blkid -c /dev/null -o value -s UUID "$device")
+	echo "UUID=$fs_uuid /boot/firmware vfat errors=remount-ro 0 3" \
+	     >>"$rootdir"/etc/fstab
+	;;
+esac
 
 mount_file_systems
 trap unmount_file_systems EXIT
