raspberry3: New image and target for Raspberry Pi 3
This is still a 32bit binary image. This is a stop gap measure until the real
64bit version is available. The 64bit version is not ready yet and images meant
for Raspberry Pi 2 are not working for Raspberry Pi 3 due to different in u-boot
binary required. The image also uses a DTB that is specifically meant for
Raspberry Pi 3.

Signed-off-by: Sunil Mohan Adapa <sunil@medhas.org>
Reviewed-by: James Valleroy <jvalleroy@mailbox.org>

diff --git a/freedommaker/freedombox-customize b/freedommaker/freedombox-customize
--- a/freedommaker/freedombox-customize
+++ b/freedommaker/freedombox-customize
@@ -110,9 +110,9 @@ unmount_file_systems() {
     umount "$rootdir/sys" || true
 
     case "$MACHINE" in
-	raspberry2)
-	    umount "$rootdir/boot/firmware" || true
-	    ;;
+        raspberry2 | raspberry3)
+            umount "$rootdir/boot/firmware" || true
+        ;;
     esac
 }
 
@@ -132,30 +132,30 @@ image="$(cd "$(dirname "$2")"; pwd)/$(basename "$2")"
 
 # Create vfat /boot/firmware partition for devices that need it.
 case "$MACHINE" in
-    raspberry2)
-	umount "$rootdir/boot"
-	umount "$rootdir"
-	kpartx -dvs "$image"
+    raspberry2 | raspberry3)
+        umount "$rootdir/boot"
+        umount "$rootdir"
+        kpartx -dvs "$image"
 
-	parted -s "$image" mkpart primary 0% 60MiB
+        parted -s "$image" mkpart primary 0% 60MiB
 
-	# Reorder partitions by start offset
-	sfdisk --reorder "$image"
+        # Reorder partitions by start offset
+        sfdisk --reorder "$image"
 
-	device=/dev/mapper/$(kpartx -avs "$image" \
-				    | awk '/^add map / {print $3; exit}')
-	mkfs -t vfat "$device"
-	parted -s "$image" set 1 lba on
+        device=/dev/mapper/$(kpartx -avs "$image" \
+            | awk '/^add map / {print $3; exit}')
+        mkfs -t vfat "$device"
+        parted -s "$image" set 1 lba on
 
-	mount -t btrfs "${device%?}3" "$rootdir"
-	mount -t ext2 "${device%?}2" "$rootdir"/boot
-	mkdir "$rootdir/boot/firmware"
-	mount -t vfat "$device" "$rootdir/boot/firmware"
+        mount -t btrfs "${device%?}3" "$rootdir"
+        mount -t ext2 "${device%?}2" "$rootdir"/boot
+        mkdir "$rootdir/boot/firmware"
+        mount -t vfat "$device" "$rootdir/boot/firmware"
 
-	fs_uuid=$(blkid -c /dev/null -o value -s UUID "$device")
-	echo "UUID=$fs_uuid /boot/firmware vfat errors=remount-ro 0 3" \
-	     >>"$rootdir"/etc/fstab
-	;;
+        fs_uuid=$(blkid -c /dev/null -o value -s UUID "$device")
+        echo "UUID=$fs_uuid /boot/firmware vfat errors=remount-ro 0 3" \
+             >>"$rootdir"/etc/fstab
+        ;;
 esac
 
 mount_file_systems
